'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("activiser.OutlookAddIn.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property activiser() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("activiser", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to about activiser™....
        '''</summary>
        Friend ReadOnly Property ActiviserAboutButtonCaption() As String
            Get
                Return ResourceManager.GetString("ActiviserAboutButtonCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to activiser™.
        '''</summary>
        Friend ReadOnly Property ActiviserAboutButtonToolTip() As String
            Get
                Return ResourceManager.GetString("ActiviserAboutButtonToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Activiser.
        '''</summary>
        Friend ReadOnly Property ActiviserCommandBarName() As String
            Get
                Return ResourceManager.GetString("ActiviserCommandBarName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to activiser™.
        '''</summary>
        Friend ReadOnly Property activiserFormTitle() As String
            Get
                Return ResourceManager.GetString("activiserFormTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;p class=&quot;intro&quot;&gt;activiser™ Web Service.
        '''</summary>
        Friend ReadOnly Property ActiviserWebServiceMagic() As String
            Get
                Return ResourceManager.GetString("ActiviserWebServiceMagic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}; {1}.
        '''</summary>
        Friend ReadOnly Property AppointmentLocationTemplate() As String
            Get
                Return ResourceManager.GetString("AppointmentLocationTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ({0}) {1}.
        '''</summary>
        Friend ReadOnly Property AppointmentSubjectTemplate() As String
            Get
                Return ResourceManager.GetString("AppointmentSubjectTemplate", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property BuilderDialog_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BuilderDialog_delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Calendar.
        '''</summary>
        Friend ReadOnly Property CalendarFolderName() As String
            Get
                Return ResourceManager.GetString("CalendarFolderName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select a client..
        '''</summary>
        Friend ReadOnly Property ClientRequired() As String
            Get
                Return ResourceManager.GetString("ClientRequired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Communication with Web Service successful..
        '''</summary>
        Friend ReadOnly Property CommunicationWithWebServiceSuccessful() As String
            Get
                Return ResourceManager.GetString("CommunicationWithWebServiceSuccessful", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Configure() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Configure", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Configure....
        '''</summary>
        Friend ReadOnly Property ConfigureCaption() As String
            Get
                Return ResourceManager.GetString("ConfigureCaption", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property ConfigureMask() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ConfigureMask", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select a consultant to assign the request to..
        '''</summary>
        Friend ReadOnly Property ConsultantRequired() As String
            Get
                Return ResourceManager.GetString("ConsultantRequired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Context Menu.
        '''</summary>
        Friend ReadOnly Property ContextMenuCommandBarName() As String
            Get
                Return ResourceManager.GetString("ContextMenuCommandBarName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New activiser™ Request....
        '''</summary>
        Friend ReadOnly Property ContextMenuNewRequestCaption() As String
            Get
                Return ResourceManager.GetString("ContextMenuNewRequestCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open activiser™ Request....
        '''</summary>
        Friend ReadOnly Property ContextMenuOpenRequestCaption() As String
            Get
                Return ResourceManager.GetString("ContextMenuOpenRequestCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Schedule activiser™ Request....
        '''</summary>
        Friend ReadOnly Property ContextMenuScheduleRequestCaption() As String
            Get
                Return ResourceManager.GetString("ContextMenuScheduleRequestCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Username should be specified in the format &lt;username&gt;@&lt;domainname&gt; or &lt;domain&gt;\&lt;username&gt;.
        '''</summary>
        Friend ReadOnly Property Credential2KHelpInfo() As String
            Get
                Return ResourceManager.GetString("Credential2KHelpInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please supply login information for your proxy server at {0}
        '''{1}.
        '''</summary>
        Friend ReadOnly Property CredentialsProxyCredentialPrompt() As String
            Get
                Return ResourceManager.GetString("CredentialsProxyCredentialPrompt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SOFTWARE\activiser™\credentialCache.
        '''</summary>
        Friend ReadOnly Property CredentialsRegistryBase() As String
            Get
                Return ResourceManager.GetString("CredentialsRegistryBase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please supply login information for your activiser web service at {0}
        '''{1}.
        '''</summary>
        Friend ReadOnly Property CredentialsWebServiceCredentialPrompt() As String
            Get
                Return ResourceManager.GetString("CredentialsWebServiceCredentialPrompt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Username should be specified in the format &lt;username&gt;@&lt;domainname&gt; or &lt;domain&gt;\&lt;username&gt;.
        '''</summary>
        Friend ReadOnly Property CredentialXPHelpInfo() As String
            Get
                Return ResourceManager.GetString("CredentialXPHelpInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ddd {0}.
        '''</summary>
        Friend ReadOnly Property DatePickerFormat() As String
            Get
                Return ResourceManager.GetString("DatePickerFormat", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property DeleteHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DeleteHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to save changes?.
        '''</summary>
        Friend ReadOnly Property DoYouWantToSaveChanges() As String
            Get
                Return ResourceManager.GetString("DoYouWantToSaveChanges", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error communicating with activiser™ web service.
        '''</summary>
        Friend ReadOnly Property ErrorCommunicatingWithActiviserWebService() As String
            Get
                Return ResourceManager.GetString("ErrorCommunicatingWithActiviserWebService", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error initialising activiser™ Add-In.
        '''</summary>
        Friend ReadOnly Property ErrorInitialisingActiviserAddIn() As String
            Get
                Return ResourceManager.GetString("ErrorInitialisingActiviserAddIn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error saving appointment and/or request.
        '''</summary>
        Friend ReadOnly Property ErrorSavingAppointmentAndOrRequest() As String
            Get
                Return ResourceManager.GetString("ErrorSavingAppointmentAndOrRequest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error saving request.
        '''</summary>
        Friend ReadOnly Property ErrorSavingRequest() As String
            Get
                Return ResourceManager.GetString("ErrorSavingRequest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error saving request to activiser™.
        '''</summary>
        Friend ReadOnly Property ErrorSavingRequestToActiviser() As String
            Get
                Return ResourceManager.GetString("ErrorSavingRequestToActiviser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to create request form: {0}.
        '''</summary>
        Friend ReadOnly Property ExplorerWrapperErrorCreatingRequestForm() As String
            Get
                Return ResourceManager.GetString("ExplorerWrapperErrorCreatingRequestForm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to open appointment: {0}.
        '''</summary>
        Friend ReadOnly Property ExplorerWrapperErrorGettingAppointmment() As String
            Get
                Return ResourceManager.GetString("ExplorerWrapperErrorGettingAppointmment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to authenticate with web service..
        '''</summary>
        Friend ReadOnly Property FailedToAuthenticateWithWebService() As String
            Get
                Return ResourceManager.GetString("FailedToAuthenticateWithWebService", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to activiser™ Outlook Add-In.
        '''</summary>
        Friend ReadOnly Property HttpUserAgentString() As String
            Get
                Return ResourceManager.GetString("HttpUserAgentString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Could not find Machine Policy level. Code Access Security is not configured for this application..
        '''</summary>
        Friend ReadOnly Property InstallerErrorCouldNotFindMachinePolicyLevel() As String
            Get
                Return ResourceManager.GetString("InstallerErrorCouldNotFindMachinePolicyLevel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to uninstall code access security:\n\n.
        '''</summary>
        Friend ReadOnly Property InstallerErrorUnableToUninstallCodeAccessSecurity() As String
            Get
                Return ResourceManager.GetString("InstallerErrorUnableToUninstallCodeAccessSecurity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /configuration/userSettings/activiser.OutlookAddIn.MySettings/setting[@name=&quot;activiserServerUrl&quot;].
        '''</summary>
        Friend ReadOnly Property InstallerServerUrlXPathQuery() As String
            Get
                Return ResourceManager.GetString("InstallerServerUrlXPathQuery", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property internetconnection() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("internetconnection", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error opening Activiser appointment; loading default appointment form.
        '''</summary>
        Friend ReadOnly Property LoadingDefaultAppointmentForm() As String
            Get
                Return ResourceManager.GetString("LoadingDefaultAppointmentForm", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Login() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Login", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Login....
        '''</summary>
        Friend ReadOnly Property LoginCaption() As String
            Get
                Return ResourceManager.GetString("LoginCaption", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property LoginMask() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LoginMask", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unknown username or incorrect password, please try again..
        '''</summary>
        Friend ReadOnly Property LogInOutLoginFailure() As String
            Get
                Return ResourceManager.GetString("LogInOutLoginFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unhandled error during login..
        '''</summary>
        Friend ReadOnly Property LogInOutUnhandledError() As String
            Get
                Return ResourceManager.GetString("LogInOutUnhandledError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Re-link consultant {0} to domain user {1} ?.
        '''</summary>
        Friend ReadOnly Property LogInOutUserLinkConfirmationTemplate() As String
            Get
                Return ResourceManager.GetString("LogInOutUserLinkConfirmationTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error linking activiser user to network user, please contact your administrator.
        '''</summary>
        Friend ReadOnly Property LogInOutUserLinkFailure() As String
            Get
                Return ResourceManager.GetString("LogInOutUserLinkFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to authenticate with web service..
        '''</summary>
        Friend ReadOnly Property LogInOutWebServiceAuthenticationFailure() As String
            Get
                Return ResourceManager.GetString("LogInOutWebServiceAuthenticationFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error communicating with activiser Web Service: {0}.
        '''</summary>
        Friend ReadOnly Property LogInOutWebServiceCommunicationFailure() As String
            Get
                Return ResourceManager.GetString("LogInOutWebServiceCommunicationFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Communication with Web Service successful..
        '''</summary>
        Friend ReadOnly Property LogInOutWebServiceCommunicationSuccessful() As String
            Get
                Return ResourceManager.GetString("LogInOutWebServiceCommunicationSuccessful", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Web Service login test failed.
        '''</summary>
        Friend ReadOnly Property LoginOutWebServiceLoginTestFailed() As String
            Get
                Return ResourceManager.GetString("LoginOutWebServiceLoginTestFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Web Service login test successful.
        '''</summary>
        Friend ReadOnly Property LoginOutWebServiceLoginTestSuccessful() As String
            Get
                Return ResourceManager.GetString("LoginOutWebServiceLoginTestSuccessful", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Logo16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Logo16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Logo16Mask() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Logo16Mask", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Logout() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Logout", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Logout....
        '''</summary>
        Friend ReadOnly Property LogoutCaption() As String
            Get
                Return ResourceManager.GetString("LogoutCaption", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property LogoutMask() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LogoutMask", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning: you are not logged on to activiser™ Web Service {0}.
        '''Unable to load activiser™ Appointment..
        '''</summary>
        Friend ReadOnly Property MustBeLoggedOn() As String
            Get
                Return ResourceManager.GetString("MustBeLoggedOn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Activiser Request....
        '''</summary>
        Friend ReadOnly Property NewActiviserRequest() As String
            Get
                Return ResourceManager.GetString("NewActiviserRequest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;New&apos; status for request undefined..
        '''</summary>
        Friend ReadOnly Property NewStatusForRequestUndefined() As String
            Get
                Return ResourceManager.GetString("NewStatusForRequestUndefined", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No data returned from server.
        '''</summary>
        Friend ReadOnly Property NoDataReturnedFromServer() As String
            Get
                Return ResourceManager.GetString("NoDataReturnedFromServer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;No Description&gt;.
        '''</summary>
        Friend ReadOnly Property NoDescription() As String
            Get
                Return ResourceManager.GetString("NoDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please log on to the activiser™ web service before attempting this operation.
        '''</summary>
        Friend ReadOnly Property NotLoggedOnExceptionMessage() As String
            Get
                Return ResourceManager.GetString("NotLoggedOnExceptionMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SOFTWARE\activiser™\OutlookAddIn.
        '''</summary>
        Friend ReadOnly Property OutlookAddInRegistryBase() As String
            Get
                Return ResourceManager.GetString("OutlookAddInRegistryBase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IPM.Appointment.ActiviserRequest.
        '''</summary>
        Friend ReadOnly Property OutlookAppointmentClass() As String
            Get
                Return ResourceManager.GetString("OutlookAppointmentClass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error saving appointment: {0}.
        '''</summary>
        Friend ReadOnly Property OutlookRequestFormAppointmentSaveError() As String
            Get
                Return ResourceManager.GetString("OutlookRequestFormAppointmentSaveError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error saving request: {0}.
        '''</summary>
        Friend ReadOnly Property OutlookRequestFormRequestSaveError() As String
            Get
                Return ResourceManager.GetString("OutlookRequestFormRequestSaveError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to General save error: {0}.
        '''</summary>
        Friend ReadOnly Property OutlookRequestFormSaveError() As String
            Get
                Return ResourceManager.GetString("OutlookRequestFormSaveError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ServerUrl.
        '''</summary>
        Friend ReadOnly Property RegistryServerUrlValueName() As String
            Get
                Return ResourceManager.GetString("RegistryServerUrlValueName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SetupDate.
        '''</summary>
        Friend ReadOnly Property RegistrySetupDateValueName() As String
            Get
                Return ResourceManager.GetString("RegistrySetupDateValueName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reminder Time must be an integer value and a description, separated by a comma..
        '''</summary>
        Friend ReadOnly Property ReminderTimeParseError() As String
            Get
                Return ResourceManager.GetString("ReminderTimeParseError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to activiser™ Request Appointment - {0}.
        '''</summary>
        Friend ReadOnly Property RequestDialogTitleFormat() As String
            Get
                Return ResourceManager.GetString("RequestDialogTitleFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RequestNumber.
        '''</summary>
        Friend ReadOnly Property RequestNumberPropertyName() As String
            Get
                Return ResourceManager.GetString("RequestNumberPropertyName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RequestUid.
        '''</summary>
        Friend ReadOnly Property RequestUidPropertyName() As String
            Get
                Return ResourceManager.GetString("RequestUidPropertyName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to $SHARED.
        '''</summary>
        Friend ReadOnly Property SharedMessagesKey() As String
            Get
                Return ResourceManager.GetString("SharedMessagesKey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please provide a short description of the problem..
        '''</summary>
        Friend ReadOnly Property ShortDescriptionRequired() As String
            Get
                Return ResourceManager.GetString("ShortDescriptionRequired", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property SplashLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SplashLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to activiser™ Add-In for Microsoft Outlook 2003.
        '''</summary>
        Friend ReadOnly Property SplashScreenApplicationTitle() As String
            Get
                Return ResourceManager.GetString("SplashScreenApplicationTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to version {0}.{1}.{2}.{3}.
        '''</summary>
        Friend ReadOnly Property SplashScreenVersionTemplate() As String
            Get
                Return ResourceManager.GetString("SplashScreenVersionTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {1}({0}): string not found.
        '''</summary>
        Friend ReadOnly Property StringNotFound() As String
            Get
                Return ResourceManager.GetString("StringNotFound", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property TaskHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TaskHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Request....
        '''</summary>
        Friend ReadOnly Property ToolBarNewRequestCaption() As String
            Get
                Return ResourceManager.GetString("ToolBarNewRequestCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open Request....
        '''</summary>
        Friend ReadOnly Property ToolBarOpenRequestCaption() As String
            Get
                Return ResourceManager.GetString("ToolBarOpenRequestCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Schedule Request....
        '''</summary>
        Friend ReadOnly Property ToolBarScheduleRequestCaption() As String
            Get
                Return ResourceManager.GetString("ToolBarScheduleRequestCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Explorer activated @ {0}.
        '''</summary>
        Friend ReadOnly Property TRACEMESSAGEExplorerActivated() As String
            Get
                Return ResourceManager.GetString("TRACEMESSAGEExplorerActivated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Explorer closed @ {0}.
        '''</summary>
        Friend ReadOnly Property TRACEMESSAGEExplorerClosed() As String
            Get
                Return ResourceManager.GetString("TRACEMESSAGEExplorerClosed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Explorer deactivated @ {0}.
        '''</summary>
        Friend ReadOnly Property TRACEMESSAGEExplorerDeactivated() As String
            Get
                Return ResourceManager.GetString("TRACEMESSAGEExplorerDeactivated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Explorer folder switch to {0} @ {1}.
        '''</summary>
        Friend ReadOnly Property TRACEMESSAGEExplorerFolderSwitch() As String
            Get
                Return ResourceManager.GetString("TRACEMESSAGEExplorerFolderSwitch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Explorer selection change @ {0}.
        '''</summary>
        Friend ReadOnly Property TRACEMESSAGEExplorerSelectionChange() As String
            Get
                Return ResourceManager.GetString("TRACEMESSAGEExplorerSelectionChange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ExplorerWrapper ignoring click event, my tag = &apos;{0}&apos;/&apos;{1}&apos;, ctrl tag = &apos;{2}&apos;.
        '''</summary>
        Friend ReadOnly Property TRACEMESSAGEIgnoringClickEvent() As String
            Get
                Return ResourceManager.GetString("TRACEMESSAGEIgnoringClickEvent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to load request data.
        '''</summary>
        Friend ReadOnly Property UnableToLoadRequestData() As String
            Get
                Return ResourceManager.GetString("UnableToLoadRequestData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to load request status list.
        '''</summary>
        Friend ReadOnly Property UnableToLoadRequestStatusList() As String
            Get
                Return ResourceManager.GetString("UnableToLoadRequestStatusList", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property user() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property users2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("users2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
