Module MessageConstants

    Friend Const RES_AboutCaption As String = "AboutCaption"
    Friend Const RES_AboutToolTip As String = "AboutToolTip"
    Friend Const RES_AppointmentLocationTemplate As String = "AppointmentLocationTemplate"
    Friend Const RES_AppointmentSaveError As String = "AppointmentSaveError"
    Friend Const RES_AppointmentSubjectTemplate As String = "AppointmentSubjectTemplate"
    Friend Const RES_ClientRequired As String = "ClientRequired"
    Friend Const RES_ConfigureCaption As String = "ConfigureCaption"
    Friend Const RES_ConfirmUndoChanges As String = "ConfirmUndoChanges"
    Friend Const RES_ConsultantRequired As String = "ConsultantRequired"
    Friend Const RES_DatePickerFormat As String = "DatePickerFormat"
    Friend Const RES_DoYouWantToSaveChanges As String = "DoYouWantToSaveChanges"
    Friend Const RES_ErrorCommunicatingWithActiviserWebService As String = "ErrorCommunicatingWithActiviserWebService"
    Friend Const RES_ErrorCreatingRequestForm As String = "ErrorCreatingRequestForm"
    Friend Const RES_ErrorGettingAppointmment As String = "ErrorGettingAppointmment"
    Friend Const RES_ErrorInitialisingActiviserAddIn As String = "ErrorInitialisingActiviserAddIn"
    Friend Const RES_ErrorSavingAppointmentAndOrRequest As String = "ErrorSavingAppointmentAndOrRequest"
    Friend Const RES_ErrorSavingRequest As String = "ErrorSavingRequest"
    Friend Const RES_LoadingDefaultAppointmentForm As String = "LoadingDefaultAppointmentForm"
    Friend Const RES_LoginCaption As String = "LoginCaption"
    Friend Const RES_LogoutCaption As String = "LogoutCaption"
    Friend Const RES_MustBeLoggedOn As String = "MustBeLoggedOn"
    Friend Const RES_NewStatusForRequestUndefined As String = "NewStatusForRequestUndefined"
    Friend Const RES_NoDataReturnedFromServer As String = "NoDataReturnedFromServer "
    Friend Const RES_NoDescription As String = "NoDescription"
    Friend Const RES_OutlookAppointmentClass As String = "OutlookAppointmentClass"
    Friend Const RES_ReminderTimeParseError As String = "ReminderTimeParseError"
    Friend Const RES_SaveRequestErrorKey As String = "ErrorSavingRequestToActiviser"
    Friend Const RES_ShortDescriptionRequired As String = "ShortDescriptionRequired"

    Friend Const RES_ContextMenuNewRequestCaption As String = "ContextMenuNewRequestCaption"
    Friend Const RES_ContextMenuOpenRequestCaption As String = "ContextMenuOpenRequestCaption"
    Friend Const RES_ContextMenuScheduleRequestCaption As String = "ContextMenuScheduleRequestCaption"

    Friend Const RES_ToolBarNewRequestCaption As String = "ToolBarNewRequestCaption"
    Friend Const RES_ToolBarOpenRequestCaption As String = "ToolBarOpenRequestCaption"
    Friend Const RES_ToolBarScheduleRequestCaption As String = "ToolBarScheduleRequestCaption"

    Friend Const RES_UnableToLoadAppointment As String = "UnableToLoadAppointment"
    Friend Const RES_UnableToLoadRequestStatusList As String = "UnableToLoadRequestStatusList"

    Friend Const RES_RequestDialogTitleFormat As String = "RequestDialogTitleFormat"

    ' Not resource strings, just normal constants!

    Friend Const STR_Apostrophe As String = "'"
    Friend Const STR_ClientList As String = "ClientList"
    Friend Const STR_ClientSiteUID As String = "ClientSiteUID"
    Friend Const STR_ClientSiteUidFilterTemplate As String = "ClientSiteUid='{0}'"
    Friend Const STR_Comma As String = ","
    Friend Const STR_ConsultantList As String = "ConsultantList"
    Friend Const STR_ConsultantUid As String = "ConsultantUid"
    Friend Const STR_Description As String = "Description"
    Friend Const STR_MAPI As String = "MAPI"
    Friend Const STR_Minutes As String = "Minutes"
    Friend Const STR_Name As String = "Name"
    Friend Const STR_RequestList As String = "RequestList"
    Friend Const STR_RequestNumber As String = "RequestNumber"
    Friend Const STR_RequestSaveError As String = "RequestSaveError"
    Friend Const STR_RequestUID As String = "RequestUid"
    Friend Const STR_SaveError As String = "SaveError"
    Friend Const STR_SiteName As String = "SiteName"
    Friend Const STR_SiteNameContainsFilterTemplate As String = "SiteName like '%{0}%'"
    Friend Const STR_SiteNameStartsWithTemplate As String = "SiteName like '{0}%'"
    Friend Const STR_TwoApostrophes As String = "''"

End Module
