'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("activiser.LanguageEditor.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property activiser() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("activiser", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to activiser™ Language Editor.
        '''</summary>
        Friend ReadOnly Property activiserFormTitle() As String
            Get
                Return ResourceManager.GetString("activiserFormTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;p class=&quot;intro&quot;&gt;activiser™ Web Service.
        '''</summary>
        Friend ReadOnly Property ActiviserWebServiceMagic() As String
            Get
                Return ResourceManager.GetString("ActiviserWebServiceMagic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SOFTWARE\activiser™\Console.
        '''</summary>
        Friend ReadOnly Property ConsoleRegistryBase() As String
            Get
                Return ResourceManager.GetString("ConsoleRegistryBase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property Credential2KHelpInfo() As String
            Get
                Return ResourceManager.GetString("Credential2KHelpInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please supply login information for your activiser web service at {0}
        '''{1}.
        '''</summary>
        Friend ReadOnly Property CredentialPrompt() As String
            Get
                Return ResourceManager.GetString("CredentialPrompt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SOFTWARE\activiser™\credentialCache.
        '''</summary>
        Friend ReadOnly Property CredentialsRegistryBase() As String
            Get
                Return ResourceManager.GetString("CredentialsRegistryBase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Username should be specified in the format &lt;username&gt;@&lt;domainname&gt; or &lt;domain&gt;\&lt;username&gt;.
        '''</summary>
        Friend ReadOnly Property CredentialXPHelpInfo() As String
            Get
                Return ResourceManager.GetString("CredentialXPHelpInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unknown username or incorrect password, please try again..
        '''</summary>
        Friend ReadOnly Property LoginFailure() As String
            Get
                Return ResourceManager.GetString("LoginFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please supply login information for your proxy server at {0}{1}.
        '''</summary>
        Friend ReadOnly Property ProxyCredentialPrompt() As String
            Get
                Return ResourceManager.GetString("ProxyCredentialPrompt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ServerUrl.
        '''</summary>
        Friend ReadOnly Property RegistryServerUrlValueName() As String
            Get
                Return ResourceManager.GetString("RegistryServerUrlValueName", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property SaveAllHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SaveAllHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SaveAsWebPageHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SaveAsWebPageHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property saveHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("saveHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SplashLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SplashLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TaskHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TaskHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unanticipated Error has occurred during login..
        '''</summary>
        Friend ReadOnly Property UnhandledError() As String
            Get
                Return ResourceManager.GetString("UnhandledError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Re-link consultant {0} to domain user {1} ?.
        '''</summary>
        Friend ReadOnly Property UserLinkConfirmationTemplate() As String
            Get
                Return ResourceManager.GetString("UserLinkConfirmationTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error linking activiser user to network user, please contact your administrator.
        '''</summary>
        Friend ReadOnly Property UserLinkFailure() As String
            Get
                Return ResourceManager.GetString("UserLinkFailure", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property users2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("users2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to authenticate with web service..
        '''</summary>
        Friend ReadOnly Property WebServiceAuthenticationFailure() As String
            Get
                Return ResourceManager.GetString("WebServiceAuthenticationFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error communicating with activiser Web Service.
        '''</summary>
        Friend ReadOnly Property WebServiceCommunicationFailure() As String
            Get
                Return ResourceManager.GetString("WebServiceCommunicationFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Communication with Web Service successful..
        '''</summary>
        Friend ReadOnly Property WebServiceCommunicationSuccessful() As String
            Get
                Return ResourceManager.GetString("WebServiceCommunicationSuccessful", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
