<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId:="domainname", Scope:="resource", Target:="activiser.Console.Resources.resources")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId:="ddd", Scope:="resource", Target:="activiser.Console.ConsultantSubForm.resources")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId:="yyyy", Scope:="resource", Target:="activiser.Console.ConsultantSubForm.resources")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId:="ss", Scope:="resource", Target:="activiser.Console.MainForm.resources")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId:="Mins", Scope:="resource", Target:="activiser.Console.Resources.resources")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId:="yyyy", Scope:="resource", Target:="activiser.Console.Resources.resources")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1701:ResourceStringCompoundWordsShouldBeCasedCorrectly", MessageId:="Logon", Scope:="resource", Target:="activiser.Console.LoginForm.resources")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1701:ResourceStringCompoundWordsShouldBeCasedCorrectly", MessageId:="username", Scope:="resource", Target:="activiser.Console.LoginForm.resources")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1701:ResourceStringCompoundWordsShouldBeCasedCorrectly", MessageId:="username", Scope:="resource", Target:="activiser.Console.Resources.resources")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1701:ResourceStringCompoundWordsShouldBeCasedCorrectly", MessageId:="Username", Scope:="resource", Target:="activiser.Console.Resources.resources")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId:="s", Scope:="member", Target:="activiser.Console.SignatureViewer.#DecryptSignature(System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId:="ccr", Scope:="member", Target:="activiser.Console.CustomControl.#.ctor(activiserDataSet+CustomControlRow,System.Data.DataTable,activiser.Console.CustomFormPanel)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId:="0#", Scope:="member", Target:="activiser.Console.SplashScreen.#SetUrlText(System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Mobility", "CA1601:DoNotUseTimersThatPreventPowerStateChanges", Scope:="member", Target:="activiser.Console.MainForm.#InitializeComponent()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Mobility", "CA1601:DoNotUseTimersThatPreventPowerStateChanges", Scope:="member", Target:="activiser.Console.JobAdminSubForm.#JobAdminSubForm_Load(System.Object,System.EventArgs)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="activiser")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames", MessageId:="guid", Scope:="member", Target:="activiser.Console.CustomFormPanel.#SetParentFilter(System.Guid)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames", MessageId:="guid", Scope:="member", Target:="activiser.Console.SyncNotificationDialog.#.ctor(System.String,System.Int32,System.Guid)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId:="Login", Scope:="type", Target:="activiser.Console.LoginForm")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId:="Flag", Scope:="type", Target:="activiser.Console.JobFlagGroup")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId:="logo", Scope:="member", Target:="activiser.Console.Win2KCredentials.#PromptForCredentials(System.String,System.String&,System.String&,System.String&,System.String,System.String,System.Drawing.Bitmap,System.Windows.Forms.Form)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope:="member", Target:="activiser.Console.ConsoleData.#.cctor()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope:="member", Target:="activiser.Console.JobSheet.#.cctor()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope:="member", Target:="activiser.Console.Credentials.#RejectUrlCredentials(System.Uri)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope:="member", Target:="activiser.Console.CredentialsXP.#PromptForCredentials(activiser.Console.NativeMethods+CREDUI_INFO&,System.String,System.Int32,System.String&,System.String&,System.Boolean&,activiser.Console.CredentialsXP+CREDUI_FLAGS)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope:="member", Target:="activiser.Console.TraceSupport.#TraceError(System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope:="member", Target:="activiser.Console.TraceSupport.#TraceWarning(System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope:="member", Target:="activiser.Console.Terminology..cctor()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope:="member", Target:="activiser.Console.ConsoleData..ctor()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope:="member", Target:="activiser.Console.NativeMethods+WinApi..cctor()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope:="member", Target:="activiser.Console.NativeMethods..cctor()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope:="member", Target:="activiser.Console.JobAdminSubForm..ctor()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope:="member", Target:="activiser.Console.EventLogSubForm..ctor()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope:="member", Target:="activiser.Console.CustomFormPanel..ctor(activiserDataSet+CustomFormRow)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1045:DoNotPassTypesByReference", Scope:="member", Target:="activiser.Console.CustomControl..ctor(activiserDataSet+CustomControlRow&,System.Data.DataTable)", MessageId:="0#")> 
