//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace activiser.WebService.CrmOutputGateway.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("activiser.WebService.CrmOutputGateway.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrmServiceLocation.
        /// </summary>
        internal static string ConfigCrmServiceLocationKey {
            get {
                return ResourceManager.GetString("ConfigCrmServiceLocationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrganizationName.
        /// </summary>
        internal static string ConfigOrganizationNameKey {
            get {
                return ResourceManager.GetString("ConfigOrganizationNameKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created new {0} entity from activiser {1}.
        /// </summary>
        internal static string CreatedNewEntityFromActiviser {
            get {
                return ResourceManager.GetString("CreatedNewEntityFromActiviser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating new {0} entity from activiser {1}.
        /// </summary>
        internal static string CreatingNewEntityFromActiviser {
            get {
                return ResourceManager.GetString("CreatingNewEntityFromActiviser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //MSCRMServices//2007//CrmService.asmx.
        /// </summary>
        internal static string CrmServiceBuilderPath {
            get {
                return ResourceManager.GetString("CrmServiceBuilderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ConfigError&gt;Unable to determine CRM Server configuration&lt;/ConfigError&gt;.
        /// </summary>
        internal static string DefaultTestMessage {
            get {
                return ResourceManager.GetString("DefaultTestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating activiser {0} entity as CRM {1} entity\n\tException message:{2}\n\tInnerXml:\n{3}\n\nEntity:\n{4}\nAssignee:\n{5}\n\nStackTrace:\n{6}.
        /// </summary>
        internal static string DynamicAssignErrorMessageFormat {
            get {
                return ResourceManager.GetString("DynamicAssignErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid Entity ID and a valid Owner are both required..
        /// </summary>
        internal static string DynamicAssignMissingDataMessage {
            get {
                return ResourceManager.GetString("DynamicAssignMissingDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating activiser {0} entity as CRM {1} entity\n\tException message:{2}\n\tInnerXml:\n{3}\n\nEntity:\n{4}\n\nStackTrace:\n{5}.
        /// </summary>
        internal static string DynamicInsertErrorMessageFormat {
            get {
                return ResourceManager.GetString("DynamicInsertErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported property types found in attribute map: CrmAttribute:{0}, ActiviserAttribute{1}, DataType:{2}.
        /// </summary>
        internal static string DynamicInsertUnsupportedPropertyErrorMessageFormat {
            get {
                return ResourceManager.GetString("DynamicInsertUnsupportedPropertyErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving entity from CRM.
        /// </summary>
        internal static string DynamicRetrieveFailureMessage {
            get {
                return ResourceManager.GetString("DynamicRetrieveFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating activiser {0} entity as CRM {1} entity\n\tException message:{2}\n\tInnerXml:\n{3}\n\nEntity:\n{4}\n\nStackTrace:\n{5}.
        /// </summary>
        internal static string DynamicSetStateErrorMessageFormat {
            get {
                return ResourceManager.GetString("DynamicSetStateErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid Entity ID and a valid State Value are both required..
        /// </summary>
        internal static string DynamicSetStateMissingDataMessage {
            get {
                return ResourceManager.GetString("DynamicSetStateMissingDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing CRM Data for Attribute [{0}] has a different type ({1}) than that specified in the gateway configuration ({2}).
        /// </summary>
        internal static string DynamicUpdateDataTypeMismatchWarning {
            get {
                return ResourceManager.GetString("DynamicUpdateDataTypeMismatchWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating activiser {0} entity as CRM {1} entity\n\tException message:{2}\n\tInnerXml:\n{3}\n\nEntity:\n{4}\n\nStackTrace:\n{5}.
        /// </summary>
        internal static string DynamicUpdateErrorMessageFormat {
            get {
                return ResourceManager.GetString("DynamicUpdateErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity ID missing or empty.
        /// </summary>
        internal static string EntityIDMissingOrEmpty {
            get {
                return ResourceManager.GetString("EntityIDMissingOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Error&gt;Error getting CRM Service Instance for Organization&lt;/Error&gt;.
        /// </summary>
        internal static string ErrorGettingCrmServiceInstance {
            get {
                return ResourceManager.GetString("ErrorGettingCrmServiceInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving data to CRM.
        /// </summary>
        internal static string ErrorSavingDataToCRM {
            get {
                return ResourceManager.GetString("ErrorSavingDataToCRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Error&gt;&lt;Message&gt;Error testing CRM connection&lt;/Message&gt;&lt;Exception&gt;{0}&lt;/Exception&gt;&lt;/Error&gt;.
        /// </summary>
        internal static string ErrorTestingCRMConnection {
            get {
                return ResourceManager.GetString("ErrorTestingCRMConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activiser.
        /// </summary>
        internal static string EventLogName {
            get {
                return ResourceManager.GetString("EventLogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activiser Output Gateway for Microsoft CRM.
        /// </summary>
        internal static string EventLogSource {
            get {
                return ResourceManager.GetString("EventLogSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to created new {0} entity from activiser {1}.
        /// </summary>
        internal static string FailedToCreateNewEntityFromActiviser {
            get {
                return ResourceManager.GetString("FailedToCreateNewEntityFromActiviser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update {0} entity from activiser {1}: {2}.
        /// </summary>
        internal static string FailedToUpdateEntityFromActiviser {
            get {
                return ResourceManager.GetString("FailedToUpdateEntityFromActiviser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[A-Fa-f0-9]{32}$|^[A-Fa-f0-9]{8}-([A-Fa-f0-9]{4}-){3}[A-Fa-f0-9]{12}$|^{[A-Fa-f0-9]{8}-([A-Fa-f0-9]{4}-){3}[A-Fa-f0-9]{12}}?$|^\(?[A-Fa-f0-9]{8}-([A-Fa-f0-9]{4}-){3}[A-Fa-f0-9]{12}\)?$|^({)?[0xA-Fa-f0-9]{3,10}(, {0,1}[0xA-Fa-f0-9]{3,6}){2}, {0,1}({)([0xA-Fa-f0-9]{3,4}, {0,1}){7}[0xA-Fa-f0-9]{3,4}(}})$.
        /// </summary>
        internal static string guidRegex {
            get {
                return ResourceManager.GetString("guidRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid Entity ID and a valid Owner ID are both required..
        /// </summary>
        internal static string MissingDataMessage {
            get {
                return ResourceManager.GetString("MissingDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Configuration&gt;&lt;Organization&gt;{0}&lt;/Organization&gt;&lt;Server&gt;{1}&lt;/Server&gt;&lt;/Configuration&gt;.
        /// </summary>
        internal static string ParametersMessageFormat {
            get {
                return ResourceManager.GetString("ParametersMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\activiser.
        /// </summary>
        internal static string RegistryBaseKey {
            get {
                return ResourceManager.GetString("RegistryBaseKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to domain.
        /// </summary>
        internal static string RegistryDomainKey {
            get {
                return ResourceManager.GetString("RegistryDomainKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        internal static string RegistryPasswordKey {
            get {
                return ResourceManager.GetString("RegistryPasswordKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username.
        /// </summary>
        internal static string RegistryUsernameKey {
            get {
                return ResourceManager.GetString("RegistryUsernameKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway test succeeded.OrganizationId:{0}, UserId: {1}.
        /// </summary>
        internal static string TestSucceeded {
            get {
                return ResourceManager.GetString("TestSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Error&gt;Unable to connect to server&lt;/Error&gt;.
        /// </summary>
        internal static string UnableToConnectToService {
            get {
                return ResourceManager.GetString("UnableToConnectToService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated {0} entity from activiser {1}.
        /// </summary>
        internal static string UpdatedEntityFromActiviser {
            get {
                return ResourceManager.GetString("UpdatedEntityFromActiviser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating {0} entity from activiser {1}.
        /// </summary>
        internal static string UpdatingEntityFromActiviser {
            get {
                return ResourceManager.GetString("UpdatingEntityFromActiviser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;WhoAmI&gt;&lt;OrganizationId&gt;{0}&lt;/OrganizationId&gt;&lt;UserId&gt;{1}&lt;/UserId&gt;&lt;/WhoAmI&gt;.
        /// </summary>
        internal static string WhoAmIResponseFormat {
            get {
                return ResourceManager.GetString("WhoAmIResponseFormat", resourceCulture);
            }
        }
    }
}
