//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace activiser.InputGateway.CrmPlugIn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("activiser.InputGateway.CrmPlugIn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActiviserTransactionID.
        /// </summary>
        internal static string ActiviserTransactionIDKey {
            get {
                return ResourceManager.GetString("ActiviserTransactionIDKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during &apos;AssignEntity&apos; plug-in execution for entity &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string AssignEntityExceptionMessage {
            get {
                return ResourceManager.GetString("AssignEntityExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during &apos;DeleteEntity&apos; plug-in execution for entity &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string CreateEntityExceptionMessage {
            get {
                return ResourceManager.GetString("CreateEntityExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id missing from Output Parameters.
        /// </summary>
        internal static string CreateEntityIdMissingExceptionMessage {
            get {
                return ResourceManager.GetString("CreateEntityIdMissingExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrmPlugIn Installed..
        /// </summary>
        internal static string CrmPlugInInstalledMessage {
            get {
                return ResourceManager.GetString("CrmPlugInInstalledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activiser.
        /// </summary>
        internal static string EventLogName {
            get {
                return ResourceManager.GetString("EventLogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activiser CRM Plug-In.
        /// </summary>
        internal static string EventLogSource {
            get {
                return ResourceManager.GetString("EventLogSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during &apos;FinishTransaction&apos; plug-in execution for entity &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string FinishTransactionExceptionMessage {
            get {
                return ResourceManager.GetString("FinishTransactionExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning during &apos;{0}&apos; plug-in execution for entity &apos;{1}&apos;: activiser input gateway not initialized..
        /// </summary>
        internal static string NoGatewayExceptionMessageFormat {
            get {
                return ResourceManager.GetString("NoGatewayExceptionMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        internal static string OrganizationIdFormat {
            get {
                return ResourceManager.GetString("OrganizationIdFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during &apos;RouteEntity&apos; plug-in execution for entity &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string RouteEntityExceptionMessage {
            get {
                return ResourceManager.GetString("RouteEntityExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during &apos;SetEntityState&apos; plug-in execution for entity &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string SetEntityStateExceptionMessage {
            get {
                return ResourceManager.GetString("SetEntityStateExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during &apos;StartTransaction&apos; plug-in execution for entity &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string StartTransactionExceptionMessage {
            get {
                return ResourceManager.GetString("StartTransactionExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during &apos;UpdateEntity&apos; plug-in execution for entity &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string UpdateEntityExceptionMessage {
            get {
                return ResourceManager.GetString("UpdateEntityExceptionMessage", resourceCulture);
            }
        }
    }
}
