'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("activiser.Console.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property activiser() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("activiser", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to activiser™ Console.
        '''</summary>
        Friend ReadOnly Property activiserFormTitle() As String
            Get
                Return ResourceManager.GetString("activiserFormTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;p class=&quot;intro&quot;&gt;activiser™ Web Service.
        '''</summary>
        Friend ReadOnly Property ActiviserWebServiceMagic() As String
            Get
                Return ResourceManager.GetString("ActiviserWebServiceMagic", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property ButtonBG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ButtonBG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ButtonBGDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ButtonBGDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ButtonMouseDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ButtonMouseDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ButtonOver() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ButtonOver", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ButtonSelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ButtonSelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Collapse_large() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Collapse_large", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed initial data load:{0}.
        '''</summary>
        Friend ReadOnly Property ConsoleDataInitialDataLoadFailureTemplate() As String
            Get
                Return ResourceManager.GetString("ConsoleDataInitialDataLoadFailureTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SOFTWARE\activiser\Console.
        '''</summary>
        Friend ReadOnly Property ConsoleRegistryBase() As String
            Get
                Return ResourceManager.GetString("ConsoleRegistryBase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to disable user &apos;{0}&apos; ?.
        '''</summary>
        Friend ReadOnly Property ConsultantSubFormConfirmUserDisable() As String
            Get
                Return ResourceManager.GetString("ConsultantSubFormConfirmUserDisable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to load Consultant Sub Form..
        '''</summary>
        Friend ReadOnly Property ConsultantSubFormFailedToLoad() As String
            Get
                Return ResourceManager.GetString("ConsultantSubFormFailedToLoad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Passwords do not match, please re-enter.
        '''</summary>
        Friend ReadOnly Property ConsultantSubFormPasswordMismatch() As String
            Get
                Return ResourceManager.GetString("ConsultantSubFormPasswordMismatch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property Credential2KHelpInfo() As String
            Get
                Return ResourceManager.GetString("Credential2KHelpInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please supply login information for your proxy server at {0}{1}.
        '''</summary>
        Friend ReadOnly Property CredentialsProxyCredentialPrompt() As String
            Get
                Return ResourceManager.GetString("CredentialsProxyCredentialPrompt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SOFTWARE\activiser\credentialCache.
        '''</summary>
        Friend ReadOnly Property CredentialsRegistryBase() As String
            Get
                Return ResourceManager.GetString("CredentialsRegistryBase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please supply login information for your activiser web service at {0}
        '''{1}.
        '''</summary>
        Friend ReadOnly Property CredentialsWebServiceCredentialPrompt() As String
            Get
                Return ResourceManager.GetString("CredentialsWebServiceCredentialPrompt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Username should be specified in the format &lt;username&gt;@&lt;domainname&gt; or &lt;domain&gt;\&lt;username&gt;.
        '''</summary>
        Friend ReadOnly Property CredentialXPHelpInfo() As String
            Get
                Return ResourceManager.GetString("CredentialXPHelpInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The selected field is already on the form.
        '''</summary>
        Friend ReadOnly Property CustomFieldAlreadyPresent() As String
            Get
                Return ResourceManager.GetString("CustomFieldAlreadyPresent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error in custom form definition
        '''Please report this incident to your support team.
        '''Error Details:
        '''{0}.
        '''</summary>
        Friend ReadOnly Property CustomFormDefinitionError() As String
            Get
                Return ResourceManager.GetString("CustomFormDefinitionError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete this record?.
        '''</summary>
        Friend ReadOnly Property CustomFormDeleteConfirmation() As String
            Get
                Return ResourceManager.GetString("CustomFormDeleteConfirmation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Custom form must use GUID for foreign key.
        '''</summary>
        Friend ReadOnly Property CustomFormForeignKeyNotGuid() As String
            Get
                Return ResourceManager.GetString("CustomFormForeignKeyNotGuid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Custom form configured to use non-standard column in standard table.
        '''</summary>
        Friend ReadOnly Property CustomFormNonStandardColumn() As String
            Get
                Return ResourceManager.GetString("CustomFormNonStandardColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to save custom form data due to missing information.
        '''</summary>
        Friend ReadOnly Property CustomFormNullDataError() As String
            Get
                Return ResourceManager.GetString("CustomFormNullDataError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Custom form must use GUID for primary key.
        '''</summary>
        Friend ReadOnly Property CustomFormPrimaryKeyNotGuid() As String
            Get
                Return ResourceManager.GetString("CustomFormPrimaryKeyNotGuid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error getting custom data schema.
        '''</summary>
        Friend ReadOnly Property CustomFormSchemaError() As String
            Get
                Return ResourceManager.GetString("CustomFormSchemaError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Couldn&apos;t load custom for for table {0}.
        '''</summary>
        Friend ReadOnly Property CustomFormTableNotFoundTemplate() As String
            Get
                Return ResourceManager.GetString("CustomFormTableNotFoundTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Undo changes made to this record since last saved?.
        '''</summary>
        Friend ReadOnly Property CustomFormUndoChangesToCustomData() As String
            Get
                Return ResourceManager.GetString("CustomFormUndoChangesToCustomData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Control type &apos;{0}&apos; is not supported by this version of activiser™.
        '''</summary>
        Friend ReadOnly Property CustomFormUnsupportedControlType() As String
            Get
                Return ResourceManager.GetString("CustomFormUnsupportedControlType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .- 
        '''	.
        '''</summary>
        Friend ReadOnly Property DeviceIdCharsToIgnore() As String
            Get
                Return ResourceManager.GetString("DeviceIdCharsToIgnore", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property disk_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("disk_blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property document_check() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_check", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property document_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property document_error() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_error", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property document_time() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_time", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Edit_UndoHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit_UndoHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Expand_large() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Expand_large", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property find() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("find", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property history() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("history", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not signed.
        '''</summary>
        Friend ReadOnly Property JobAdminSubFormDoNotHaveSignature() As String
            Get
                Return ResourceManager.GetString("JobAdminSubFormDoNotHaveSignature", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning: Finish Time specified is before Start Time.
        '''</summary>
        Friend ReadOnly Property JobAdminSubFormFinishTimeBeforeStartTime() As String
            Get
                Return ResourceManager.GetString("JobAdminSubFormFinishTimeBeforeStartTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Signed.
        '''</summary>
        Friend ReadOnly Property JobAdminSubFormHaveSignature() As String
            Get
                Return ResourceManager.GetString("JobAdminSubFormHaveSignature", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Client Information.
        '''</summary>
        Friend ReadOnly Property JobAdminSubFormNoClientInformation() As String
            Get
                Return ResourceManager.GetString("JobAdminSubFormNoClientInformation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;None&gt;.
        '''</summary>
        Friend ReadOnly Property JobAdminSubFormNoRequestStatusID() As String
            Get
                Return ResourceManager.GetString("JobAdminSubFormNoRequestStatusID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Consultant: {0}.
        '''</summary>
        Friend ReadOnly Property JobAdminSubFormStatusBarConsultant() As String
            Get
                Return ResourceManager.GetString("JobAdminSubFormStatusBarConsultant", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not Signed.
        '''</summary>
        Friend ReadOnly Property JobAdminSubFormStatusBarDoNotHaveSignature() As String
            Get
                Return ResourceManager.GetString("JobAdminSubFormStatusBarDoNotHaveSignature", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Has Equipment.
        '''</summary>
        Friend ReadOnly Property JobAdminSubFormStatusBarHasEquipment() As String
            Get
                Return ResourceManager.GetString("JobAdminSubFormStatusBarHasEquipment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Has Notes.
        '''</summary>
        Friend ReadOnly Property JobAdminSubFormStatusBarHasNotes() As String
            Get
                Return ResourceManager.GetString("JobAdminSubFormStatusBarHasNotes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Signed.
        '''</summary>
        Friend ReadOnly Property JobAdminSubFormStatusBarHaveSignature() As String
            Get
                Return ResourceManager.GetString("JobAdminSubFormStatusBarHaveSignature", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Request #: {0}.
        '''</summary>
        Friend ReadOnly Property JobAdminSubFormStatusBarRequestNumber() As String
            Get
                Return ResourceManager.GetString("JobAdminSubFormStatusBarRequestNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Client: {0}.
        '''</summary>
        Friend ReadOnly Property JobAdminSubFormStatusBarSiteName() As String
            Get
                Return ResourceManager.GetString("JobAdminSubFormStatusBarSiteName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Update Status.
        '''</summary>
        Friend ReadOnly Property JobAdminSubFormUpdateStatusButton() As String
            Get
                Return ResourceManager.GetString("JobAdminSubFormUpdateStatusButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This service brought to you by the activiser™ system of {LicenseeName}.
        '''</summary>
        Friend ReadOnly Property JobSheetLicenseePostScript() As String
            Get
                Return ResourceManager.GetString("JobSheetLicenseePostScript", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error getting server profile.
        '''</summary>
        Friend ReadOnly Property JobSheetServerProfileError() As String
            Get
                Return ResourceManager.GetString("JobSheetServerProfileError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to activiser™ License has expired. Web service disabled..
        '''</summary>
        Friend ReadOnly Property LicenseExpiredWarning() As String
            Get
                Return ResourceManager.GetString("LicenseExpiredWarning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Current activiser™ License will expire in {0} days.
        '''</summary>
        Friend ReadOnly Property LicenseWillExpireMessageTemplate() As String
            Get
                Return ResourceManager.GetString("LicenseWillExpireMessageTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unanticipated Error has occurred during login..
        '''</summary>
        Friend ReadOnly Property LoginFormUnhandledError() As String
            Get
                Return ResourceManager.GetString("LoginFormUnhandledError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Re-link consultant {0} to domain user {1} ?.
        '''</summary>
        Friend ReadOnly Property LoginFormUserLinkConfirmationTemplate() As String
            Get
                Return ResourceManager.GetString("LoginFormUserLinkConfirmationTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error linking activiser user to network user, please contact your administrator.
        '''</summary>
        Friend ReadOnly Property LoginFormUserLinkFailure() As String
            Get
                Return ResourceManager.GetString("LoginFormUserLinkFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unknown username or incorrect password, please try again..
        '''</summary>
        Friend ReadOnly Property LogInOutLoginFailure() As String
            Get
                Return ResourceManager.GetString("LogInOutLoginFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to authenticate with web service..
        '''</summary>
        Friend ReadOnly Property LogInOutWebServiceAuthenticationFailure() As String
            Get
                Return ResourceManager.GetString("LogInOutWebServiceAuthenticationFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error communicating with activiser Web Service.
        '''</summary>
        Friend ReadOnly Property LogInOutWebServiceCommunicationFailure() As String
            Get
                Return ResourceManager.GetString("LogInOutWebServiceCommunicationFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Communication with Web Service successful..
        '''</summary>
        Friend ReadOnly Property LogInOutWebServiceCommunicationSuccessful() As String
            Get
                Return ResourceManager.GetString("LogInOutWebServiceCommunicationSuccessful", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Logo16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Logo16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Logo32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Logo32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Logo48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Logo48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ApprovalNodeTag ItemList must contain at least four items.
        '''</summary>
        Friend ReadOnly Property MainFormApprovalNodeTagItemListMessage() As String
            Get
                Return ResourceManager.GetString("MainFormApprovalNodeTagItemListMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Approval.
        '''</summary>
        Friend ReadOnly Property MainFormApprovalStatusRootNodeLabel() As String
            Get
                Return ResourceManager.GetString("MainFormApprovalStatusRootNodeLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Consultant.
        '''</summary>
        Friend ReadOnly Property MainFormConsultantRootNodeLabel() As String
            Get
                Return ResourceManager.GetString("MainFormConsultantRootNodeLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Consultant Status.
        '''</summary>
        Friend ReadOnly Property MainFormConsultantStatusRootNodeLabel() As String
            Get
                Return ResourceManager.GetString("MainFormConsultantStatusRootNodeLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fatal error loading job approval tree: {0}.
        '''</summary>
        Friend ReadOnly Property MainFormJobApprovalTreeLoadFailureMessageTemplate() As String
            Get
                Return ResourceManager.GetString("MainFormJobApprovalTreeLoadFailureMessageTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Request Admin ({0}).
        '''</summary>
        Friend ReadOnly Property MainFormRequestAdminButtonTemplate() As String
            Get
                Return ResourceManager.GetString("MainFormRequestAdminButtonTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Request Status.
        '''</summary>
        Friend ReadOnly Property MainFormRequestStatusRootNodeLabel() As String
            Get
                Return ResourceManager.GetString("MainFormRequestStatusRootNodeLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to activiser™ Management Console {2} [{0} on {1}].
        '''</summary>
        Friend ReadOnly Property MainFormTitleTemplate() As String
            Get
                Return ResourceManager.GetString("MainFormTitleTemplate", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property NoAction() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NoAction", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;None&gt;.
        '''</summary>
        Friend ReadOnly Property None() As String
            Get
                Return ResourceManager.GetString("None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;N/A&gt;.
        '''</summary>
        Friend ReadOnly Property NotAvailable() As String
            Get
                Return ResourceManager.GetString("NotAvailable", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property NotificationBackgroundImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NotificationBackgroundImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {4} 
        '''has just synchronised {2} {3} for {0} {1}.
        '''</summary>
        Friend ReadOnly Property NotificationFormat() As String
            Get
                Return ResourceManager.GetString("NotificationFormat", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property OK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error updating event descriptions.
        '''</summary>
        Friend ReadOnly Property OptionsFormErrorUpdatingEventDescriptions() As String
            Get
                Return ResourceManager.GetString("OptionsFormErrorUpdatingEventDescriptions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Server URL must start with http:// or https://.
        '''</summary>
        Friend ReadOnly Property OptionsFormUrlPrefixMessage() As String
            Get
                Return ResourceManager.GetString("OptionsFormUrlPrefixMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to activiser Web Service.
        '''</summary>
        Friend ReadOnly Property OptionsFormUrlTestKeyPhrase() As String
            Get
                Return ResourceManager.GetString("OptionsFormUrlTestKeyPhrase", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property printer2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("printer2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Refresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Refresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ServerUrl.
        '''</summary>
        Friend ReadOnly Property RegistryServerUrlValueName() As String
            Get
                Return ResourceManager.GetString("RegistryServerUrlValueName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;None&gt;.
        '''</summary>
        Friend ReadOnly Property RequestAdminSubFormNoRequestStatusID() As String
            Get
                Return ResourceManager.GetString("RequestAdminSubFormNoRequestStatusID", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property SaveAllHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SaveAllHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SaveAsWebPageHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SaveAsWebPageHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property saveHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("saveHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to administrator@localhost.
        '''</summary>
        Friend ReadOnly Property ServerProfileFormDefaultActiviserAdministratorAddress() As String
            Get
                Return ResourceManager.GetString("ServerProfileFormDefaultActiviserAdministratorAddress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to activiser@localhost.
        '''</summary>
        Friend ReadOnly Property ServerProfileFormDefaultActiviserMailAddress() As String
            Get
                Return ResourceManager.GetString("ServerProfileFormDefaultActiviserMailAddress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Message from activiser at {LicenseeName}.
        '''</summary>
        Friend ReadOnly Property ServerProfileFormDefaultJobMailSubjectTemplate() As String
            Get
                Return ResourceManager.GetString("ServerProfileFormDefaultJobMailSubjectTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to localhost.
        '''</summary>
        Friend ReadOnly Property ServerProfileFormDefaultMailServerAddress() As String
            Get
                Return ResourceManager.GetString("ServerProfileFormDefaultMailServerAddress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Greetings.
        '''
        '''Please do not reply to this message, as it an automated message from the activiser system at {LicenseeName}
        '''
        '''As requested, please find below details of work completed at your site by our consultant {Consultant.Name}.
        '''
        '''Started: {Job.StartTime}
        '''Finished: {Job.FinishTime}
        '''Travel Time: {Job.MinsTravelled} minutes
        '''
        '''Details/Equipment:
        '''{Job.JobDetails}
        '''{Job.Equipment}
        '''
        '''
        '''If you have any questions about this work, please contact us at {AdminEmail}
        '''
        '''Kind Regards,
        '''
        '''{LicenseeName}.
        '''</summary>
        Friend ReadOnly Property ServerProfileFormDefaultMailTemplate() As String
            Get
                Return ResourceManager.GetString("ServerProfileFormDefaultMailTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;Number&gt;@SMSProvider.com.
        '''</summary>
        Friend ReadOnly Property ServerProfileFormDefaultSMSAddress() As String
            Get
                Return ResourceManager.GetString("ServerProfileFormDefaultSMSAddress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You have been assigned request &lt;Request&gt; for &lt;Client&gt;. Please synchronise your activiser™ client..
        '''</summary>
        Friend ReadOnly Property ServerProfileFormDefaultSMSMessage() As String
            Get
                Return ResourceManager.GetString("ServerProfileFormDefaultSMSMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Client Name or License Key is invalid or do not match..
        '''</summary>
        Friend ReadOnly Property ServerProfileFormLicenseInvalid() As String
            Get
                Return ResourceManager.GetString("ServerProfileFormLicenseInvalid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Expiry Date: {0:dd MMM yyyy}
        '''Version: {1}
        '''Users: {2}.
        '''</summary>
        Friend ReadOnly Property ServerProfileFormLicenseTestTemplate() As String
            Get
                Return ResourceManager.GetString("ServerProfileFormLicenseTestTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to To send various alerts, and job notifications to client, the activiser™ web service needs access to an SMTP server.
        '''
        '''Please provide either the DNS domain name or IP address of your SMTP Server, and the port number (SMTP default port is 25)
        '''
        '''Additionally, please provide the &apos;activiser&apos; and &apos;administrator&apos; mail addresses. 
        '''The &apos;activiser&apos; mail address is the &apos;From&apos; address for email sent by the activiser web service.
        '''The &apos;administrator&apos; mail address is the email address of the person responsible for adm [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ServerProfileFormMailServerExplanation() As String
            Get
                Return ResourceManager.GetString("ServerProfileFormMailServerExplanation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This is a test message from the activiser™ console..
        '''</summary>
        Friend ReadOnly Property ServerProfileFormMailServerTestMessage() As String
            Get
                Return ResourceManager.GetString("ServerProfileFormMailServerTestMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to activiser console mail test.
        '''</summary>
        Friend ReadOnly Property ServerProfileFormMailServerTestSubject() As String
            Get
                Return ResourceManager.GetString("ServerProfileFormMailServerTestSubject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter the template for job completion messages to be sent to clients. 
        '''
        '''Text enclosed in braces ( &apos;{&apos; and &apos;}&apos;) and matching an escape code or field name will be replaced with the relevant text.
        '''
        '''Special escape codes:
        '''{LicenseeName} - activiser license holder name
        '''{AdminEmail} - activiser administrator email address 
        '''
        '''Any field from the Job, Request, ClientSite or Consultant Tables is valid, and must be formatted as {&lt;TableName&gt;.&lt;FieldName&gt;}, e.g.
        '''{Job.StartTime}
        '''{Job.FinishTime}
        '''{Request.RequestN [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ServerProfileFormMailTemplateExplanation() As String
            Get
                Return ResourceManager.GetString("ServerProfileFormMailTemplateExplanation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Message send failure:
        '''{0}.
        '''</summary>
        Friend ReadOnly Property ServerProfileFormMailTestFailureMessage() As String
            Get
                Return ResourceManager.GetString("ServerProfileFormMailTestFailureMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Message sent OK.
        '''</summary>
        Friend ReadOnly Property ServerProfileFormMailTestSuccessMessage() As String
            Get
                Return ResourceManager.GetString("ServerProfileFormMailTestSuccessMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to save server profile.
        '''</summary>
        Friend ReadOnly Property ServerProfileFormSaveFailureMesasge() As String
            Get
                Return ResourceManager.GetString("ServerProfileFormSaveFailureMesasge", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to $SHARED.
        '''</summary>
        Friend ReadOnly Property SharedMessagesKey() As String
            Get
                Return ResourceManager.GetString("SharedMessagesKey", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property SplashLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SplashLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to activiser management console.
        '''</summary>
        Friend ReadOnly Property SplashScreenApplicationTitle() As String
            Get
                Return ResourceManager.GetString("SplashScreenApplicationTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to version {0}.{1}.{2}.{3}.
        '''</summary>
        Friend ReadOnly Property SplashScreenVersionTemplate() As String
            Get
                Return ResourceManager.GetString("SplashScreenVersionTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Refresh Disabled.
        '''</summary>
        Friend ReadOnly Property StatusBarRefreshDisabled() As String
            Get
                Return ResourceManager.GetString("StatusBarRefreshDisabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Refresh Enabled.
        '''</summary>
        Friend ReadOnly Property StatusBarRefreshEnabled() As String
            Get
                Return ResourceManager.GetString("StatusBarRefreshEnabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to STATUS CHANGE ({0}).
        '''</summary>
        Friend ReadOnly Property StatusChangeMessageTemplate() As String
            Get
                Return ResourceManager.GetString("StatusChangeMessageTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {1}({0}): string not found.
        '''</summary>
        Friend ReadOnly Property StringNotFound() As String
            Get
                Return ResourceManager.GetString("StringNotFound", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property TaskHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TaskHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Message not found.
        '''</summary>
        Friend ReadOnly Property TerminologyMessageNotFound() As String
            Get
                Return ResourceManager.GetString("TerminologyMessageNotFound", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property text_ok() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_ok", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ToolHeadBG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ToolHeadBG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Can&apos;t add more than 200 controls to a form..
        '''</summary>
        Friend ReadOnly Property TooManyCustomFields() As String
            Get
                Return ResourceManager.GetString("TooManyCustomFields", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to print job..
        '''</summary>
        Friend ReadOnly Property UnableToPrintJob() As String
            Get
                Return ResourceManager.GetString("UnableToPrintJob", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to process activiser™ License..
        '''</summary>
        Friend ReadOnly Property UnableToProcessActiviserLicenseMessage() As String
            Get
                Return ResourceManager.GetString("UnableToProcessActiviserLicenseMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UnableToSaveCustomForm.
        '''</summary>
        Friend ReadOnly Property UnableToSaveCustomForm() As String
            Get
                Return ResourceManager.GetString("UnableToSaveCustomForm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;Unassigned&gt;.
        '''</summary>
        Friend ReadOnly Property Unassigned() As String
            Get
                Return ResourceManager.GetString("Unassigned", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning: this installation of activiser™ is currently unlicensed, web service disabled..
        '''</summary>
        Friend ReadOnly Property UnlicensedWarning() As String
            Get
                Return ResourceManager.GetString("UnlicensedWarning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unsupported Operating System.
        '''</summary>
        Friend ReadOnly Property UnsupportedOperatingSystem() As String
            Get
                Return ResourceManager.GetString("UnsupportedOperatingSystem", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property user() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property users2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("users2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property warning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Web() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Web", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
